version: "3.3"

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=videos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresa40*
    ports:
      - "5432:5432"
    volumes:
      - ./postgress_data:/var/lib/postgresql
